HOSTS:
  server7:
    roles:
      - server7
      - default
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  client7:
    roles:
      - client7
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  server6:
    roles:
      - server6
    platform:   el-6-x86_64
    box:        centos/7
    hypervisor: vagrant
  client6:
    roles:
      - client6
    platform:   el-6-x86_64
    box:        centos/7
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
