HOSTS:
  server:
    roles:
      - server
      - default
      - master
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.0-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
  ### ip:         10.10.10.101
  client:
    roles:
      - client
      - agent
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.0-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
  ###  ip:         10.10.10.102
CONFIG:
  log_level: verbose
  type:      foss
  vagrant_memsize: 256
